# Site settings
title: Jolene Lai - Fine Artist
email: enelojial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Paintings and Drawings by Jolene Lai
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jolenelaiart.com" # the base hostname & protocol for your site
twitter_username: jolenelaiart

# Build settings
markdown: kramdown

permalink: /:categories/:title/
future: true

defaults:
  -
    scope:
      path: "_posts/drawings"
    values:
      category: "drawings"
  -
    scope:
      path: "_posts/paintings"
    values:
      category: "paintings"
  -
    scope:
      path: "_posts/news"
    values:
      category: "news"
      permalink: /:categories/:year/:month/:day/:title

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

sass:
    style: :compressed
